In [1]:
pandas as pd

SyntaxError: invalid syntax (142263799.py, line 1)

In [2]:
import pandas as pd

In [3]:
pizza_sal=pd.Series([12,30,40,90,38])

In [4]:
pizza_sal

0    12
1    30
2    40
3    90
4    38
dtype: int64

In [10]:
data = {
    "name": [
        "a", "b", "c", "d", "e", "f", "g", "h", "i", "j",
        "k", "l", "m", "n", "o", "p", "q", "r", "s", "t",
        "u", "v", "w"
    ],
    "age": [
        20, 21, 23, 24, 25, 22, 26, 27, 28, 29,
        30, 31, 24, 26, 27, 32, 33, 34, 35, 36,
        37, 38, 39
    ],
    "sal": [
        40000, 50000, 343535, 45000, 52000, 48000, 55000,
        60000, 62000, 58000, 65000, 70000, 47000, 53000,
        56000, 72000, 75000, 80000, 85000, 90000,
        95000, 100000, 105000
    ]
}
df=pd.DataFrame(data)
df.shape

(23, 3)

In [11]:
print(df)

   name  age     sal
0     a   20   40000
1     b   21   50000
2     c   23  343535
3     d   24   45000
4     e   25   52000
5     f   22   48000
6     g   26   55000
7     h   27   60000
8     i   28   62000
9     j   29   58000
10    k   30   65000
11    l   31   70000
12    m   24   47000
13    n   26   53000
14    o   27   56000
15    p   32   72000
16    q   33   75000
17    r   34   80000
18    s   35   85000
19    t   36   90000
20    u   37   95000
21    v   38  100000
22    w   39  105000

In [8]:
df.shape[0]

3

In [9]:
df.columns

Index(['name', 'age', 'sal'], dtype='str')

In [12]:
pd.head(6)

AttributeError: module 'pandas' has no attribute 'head'

In [13]:
df.head(6)

  name  age     sal
0    a   20   40000
1    b   21   50000
2    c   23  343535
3    d   24   45000
4    e   25   52000
5    f   22   48000

In [16]:
df['name'].head(3
               )

0    a
1    b
2    c
Name: name, dtype: str

In [17]:
df.head()

  name  age     sal
0    a   20   40000
1    b   21   50000
2    c   23  343535
3    d   24   45000
4    e   25   52000

In [18]:
df.tail(9)

   name  age     sal
14    o   27   56000
15    p   32   72000
16    q   33   75000
17    r   34   80000
18    s   35   85000
19    t   36   90000
20    u   37   95000
21    v   38  100000
22    w   39  105000

In [21]:
print(df[df["sal"] <45000])

  name  age    sal
0    a   20  40000