In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pg236\appdata\roaming\python\python313\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pg236\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\pg236\appdata\roaming\python\python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\pg236\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.8 MB 6.5 MB/s eta 0:00:02
   ------------- -------------------------- 3.4/9.8 MB 7.5 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.8 MB 8.3 MB/s eta 0:00:01
   --------------------------------- ------ 8.1/9.8 MB 9.1 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 9.1 MB/s eta 0:00:00
Installing collected packages: pandas
Successfully installed pandas-3.0.3

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
df=pd.read_csv(r"C:\FBS\Data Analysis\Dataexploration\cars93.csv")

NameError: name 'pd' is not defined

In [3]:
import pandas as pd
df=pd.read_csv(r"C:\FBS\Data Analysis\Dataexploration\cars93.csv")

In [5]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,3259500,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,6949500,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,5965500,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,7728500,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,6150000,22,Driver only,208,4,27.0,13.0

In [6]:
print("rows:",df.shape[0])
print("columns",df.shape[1])

rows: 93
columns 10

In [7]:
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Price', 'MPG.city', 'AirBags',
       'Horsepower', 'Passengers', 'Rear.seat.room', 'Luggage.room'],
      dtype='str')

In [8]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,9.300000e+01,93.000000,93.000000,93.000000,91.000000,82.000000
mean,3.999484e+06,22.365591,143.827957,5.086022,27.829670,13.890244
std,1.980183e+06,5.619812,52.374410,1.038979,2.989072,2.997967
min,1.517000e+06,15.000000,55.000000,2.000000,19.000000,6.000000
25%,2.501000e+06,18.000000,103.000000,4.000000,26.000000,12.000000
50%,3.628500e+06,21.000000,140.000000,5.000000,27.500000,14.000000
75%,4.776500e+06,25.000000,170.000000,6.000000,30.000000,15.000000
max,1.268950e+07,46.000000,300.000000,8.000000,36.000000,22.000000

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     str
 1   Model           93 non-null     str
 2   Type            93 non-null     str
 3   Price           93 non-null     int64
 4   MPG.city        93 non-null     int64
 5   AirBags         79 non-null     str
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(2), int64(4), str(4)
memory usage: 7.4 KB

In [11]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
#handling missing value

In [12]:
df['Rear.seat.room'].mean()

np.float64(27.82967032967033)

In [13]:
df['Rear.seat.room'].median()

np.float64(27.5)

In [14]:
x=df['Rear.seat.room'].median()

In [15]:
df['Rear.seat.room']=df['Rear.seat.room'].fillna(value=x)

In [16]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room      11
dtype: int64

In [20]:
df['Luggage.room'].mean()

np.float64(13.890243902439025)

In [21]:
df['Luggage.room'].median()

np.float64(14.0)

In [22]:
t=df['Luggage.room'].median()

In [23]:
df['Luggage.room']=df['Luggage.room'].fillna(value=t)

In [25]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room       0
dtype: int64

In [ ]:
# using mode to handle string type missing data

In [26]:
df['AirBags'].mode()[0]

'Driver only'

In [27]:
x=df['AirBags'].mode()[0]

In [28]:
df['AirBags']=df['AirBags'].fillna(value=x)

In [29]:
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [30]:
# normalization 0 to 1

In [31]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,3259500,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,6949500,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,5965500,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,7728500,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,6150000,22,Driver only,208,4,27.0,13.0

In [32]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\pg236\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 3.0 MB/s eta 0:00:03
   --- ------------------------------------ 0.8/8.2 MB 2.4 MB/s eta 0:00:04
   ------- -------------------------------- 1.6/8.2 MB 2.9 MB/s eta 0:00:03
   ----------- ---------------------------- 2.4/8.2 MB 3.2 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.2 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.2 MB 3.8 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.2 MB 4.2 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 4.9 MB/s eta 0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   -- ------------------------------------- 2.1/36.5 MB 9.9 MB/s eta 0:00:04
   ---- ----------------------------------- 4.5/36.5 MB 10.7 MB/s eta 0:00:04
   ------- -------------------------------- 7.1/36.5 MB 11.2 MB/s eta 0:00:03
   ----------- ---------------------------- 10.2/36.5 MB 12.2 MB/s eta 0:00:03
   -------------- ------------------------- 13.1/36.5 MB 12.8 MB/s eta 0:00:02
   ------------------ --------------------- 16.5/36.5 MB 13.2 MB/s eta 0:00:02
   --------------------- ------------------ 19.9/36.5 MB 13.6 MB/s eta 0:00:02
   ------------------------- -------------- 23.6/36.5 MB 14.2 MB/s eta 0:00:01
   ---------------------------- ----------- 26.0/36.5 MB 13.8 MB/s eta 0:00:01
   ------------------------------ --------- 27.8/36.5 MB 13.3 MB/s eta 0:00:01
   --------------------------------- ------ 30.7/36.5 MB 13.4 MB/s eta 0:00:01
   ------------------------------------ --- 33.0/36.5 MB 13.2 MB/s eta 0:00:01
   -------------------------------------- - 35.1/36.5 MB 12.9 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 13.0 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 13.0 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 13.0 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 13.0 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 9.7 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn
Successfully installed joblib-1.5.3 narwhals-2.22.1 scikit-learn-1.9.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
from sklearn.preprocessing import MinMaxScaler

In [34]:
min_max=MinMaxScaler()

In [35]:
price_normalised=min_max.fit_transform(df[['Price']])

In [36]:
price_normalised.min()

np.float64(0.0)

In [37]:
price_normalised.max()

np.float64(1.0)

In [ ]:
# adding new normalized column into our existing dataframe

In [38]:
df['price_normalised']=price_normalised

In [ ]:
# applying standardization

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
std_scaler=StandardScaler()

In [43]:
Horsepower_std=std_scaler.fit_transform(df[['Horsepower']])

In [44]:
df['Horsepower_std']=Horsepower_std

In [45]:
df['Horsepower_std'].min()

np.float64(-1.705210877485415)

In [46]:
df['Horsepower_std'].max()

np.float64(2.998000579179055)

In [47]:
# data encoding

In [48]:
# one hot encoding

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Manufacturer      93 non-null     str
 1   Model             93 non-null     str
 2   Type              93 non-null     str
 3   Price             93 non-null     int64
 4   MPG.city          93 non-null     int64
 5   AirBags           93 non-null     str
 6   Horsepower        93 non-null     int64
 7   Passengers        93 non-null     int64
 8   Rear.seat.room    93 non-null     float64
 9   Luggage.room      93 non-null     float64
 10  price_normalised  93 non-null     float64
 11  Horsepower_std    93 non-null     float64
dtypes: float64(4), int64(4), str(4)
memory usage: 8.8 KB

In [50]:
df_encoded=pd.get_dummies(df)

In [51]:
df_encoded.shape[1]

141

In [52]:
df_encoded.shape

(93, 141)

In [53]:
len(df['Model'].unique())

93

In [54]:
len(df['Manufacturer'].unique())

32

In [55]:
len(df['Type'].unique())

6

In [56]:
len(df['AirBags'].unique())

2

In [57]:
df.shape

(93, 12)

In [58]:
12+2+32+6+93

145

In [59]:
145-4 # colums are replace

141

In [61]:
df_encoded.shape

(93, 141)

In [62]:
#label encoding

In [64]:
df.AirBags.unique()

<StringArray>
['Driver only', 'Driver & Passenger']
Length: 2, dtype: str

In [65]:
df.Type.unique()

<StringArray>
['Small', 'Midsize', 'Compact', 'Large', 'Sporty', 'Van']
Length: 6, dtype: str

In [66]:
from sklearn.preprocessing import LabelEncoder

In [67]:
label_encoder=LabelEncoder()

In [68]:
df_encoded=label_encoder.fit_transform(df["Type"])

In [69]:
df_encoded

array([3, 2, 0, 2, 2, 2, 1, 1, 2, 1, 2, 0, 0, 4, 2, 5, 5, 1, 4, 1, 0, 1,
       3, 3, 0, 5, 2, 4, 3, 1, 3, 3, 0, 4, 4, 5, 2, 1, 3, 4, 4, 3, 0, 3,
       3, 4, 2, 2, 2, 2, 2, 1, 3, 3, 0, 5, 4, 0, 2, 4, 2, 3, 2, 3, 0, 5,
       2, 0, 2, 5, 1, 4, 3, 0, 4, 2, 1, 0, 3, 3, 3, 0, 3, 3, 4, 2, 5, 3,
       5, 0, 4, 0, 2])

In [70]:
df['Type_encoded']=df_encoded