In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\FBS\Data Analysis\Dataexploration\Missing Value Fortune_10.csv")

In [3]:
df.head()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%

In [4]:
df.isna().sum()

ID           0
Date         0
Name         1
Companies    0
Inception    2
Revenue      1
Expenses     1
Profit       1
Growth       0
dtype: int64

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Date       10 non-null     str
 2   Name       9 non-null      str
 3   Companies  10 non-null     str
 4   Inception  8 non-null      float64
 5   Revenue    9 non-null      str
 6   Expenses   9 non-null      str
 7   Profit     9 non-null      float64
 8   Growth     10 non-null     str
dtypes: float64(2), int64(1), str(6)
memory usage: 852.0 bytes

In [6]:
                                                                                                                                                            df.ffill()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371","6,482,465 Dollars",11412916.0,20%
2,3,No,Stripfind,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,2013.0,"$10,573,990","7,435,363 Dollars",6597557.0,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,2011.0,"$13,898,119","6,249,498 Dollars",3005116.0,6%
7,8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [7]:
df.head()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%

In [8]:
df['Profit'].mean()

np.float64(6739094.222222222)

In [13]:
x=df['Profit'].median()

In [14]:
df['Profit'].fillna(value=x)

0     5274553.0
1    11412916.0
2     3005820.0
3     6597557.0
4     5573830.0
5     8427816.0
6     3005116.0
7     5573830.0
8    11901180.0
9     5453060.0
Name: Profit, dtype: float64

In [15]:
df.isna().sum()

ID           0
Date         0
Name         1
Companies    0
Inception    2
Revenue      1
Expenses     1
Profit       1
Growth       0
dtype: int64

In [18]:
df['Profit']=df['Profit'].fillna(value=x)

In [19]:
df.isna().sum()

ID           0
Date         0
Name         1
Companies    0
Inception    2
Revenue      1
Expenses     1
Profit       0
Growth       0
profit       0
dtype: int64

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Date       10 non-null     str
 2   Name       9 non-null      str
 3   Companies  10 non-null     str
 4   Inception  8 non-null      float64
 5   Revenue    9 non-null      str
 6   Expenses   9 non-null      str
 7   Profit     10 non-null     float64
 8   Growth     10 non-null     str
 9   profit     10 non-null     float64
dtypes: float64(3), int64(1), str(6)
memory usage: 932.0 bytes

In [21]:
df['Expenses'].mode()

0    3,878,113 Dollars
1    3,878,153 Dollars
2    5,470,303 Dollars
3    5,635,276 Dollars
4    6,249,498 Dollars
5    6,482,465 Dollars
6    7,429,377 Dollars
7    7,435,363 Dollars
8    7,591,189 Dollars
Name: Expenses, dtype: str

In [22]:
x=df['Expenses'].mode()[0]

'3,878,113 Dollars'

In [23]:
df['Expenses']=df['Expenses'].fillna(value=x)

In [24]:
df.isna().sum()

ID           0
Date         0
Name         1
Companies    0
Inception    2
Revenue      1
Expenses     0
Profit       0
Growth       0
profit       0
dtype: int64

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Date       10 non-null     str
 2   Name       9 non-null      str
 3   Companies  10 non-null     str
 4   Inception  8 non-null      float64
 5   Revenue    9 non-null      str
 6   Expenses   10 non-null     object
 7   Profit     10 non-null     float64
 8   Growth     10 non-null     str
 9   profit     10 non-null     float64
dtypes: float64(3), int64(1), object(1), str(5)
memory usage: 932.0+ bytes

In [29]:
x=df['Revenue'].mode()[0]

In [30]:
df['Revenue']=df['Revenue'].fillna(value=x)

In [31]:
df.isna().sum()

ID           0
Date         0
Name         1
Companies    0
Inception    2
Revenue      0
Expenses     0
Profit       0
Growth       0
profit       0
dtype: int64

In [33]:
x=df['Inception'].median()

In [34]:
df['Inception']=df['Inception'].fillna(value=x)

In [37]:
x=df['Name'].mode()[0]

In [38]:
df['Name']=df['Name'].fillna(value=x)

In [39]:
df.isna().sum()

ID           0
Date         0
Name         0
Companies    0
Inception    0
Revenue      0
Expenses     0
Profit       0
Growth       0
profit       0
dtype: int64

In [40]:
df.head()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth,profit
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%,5274553.0
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",5573830.0,11412916.0,20%,11412916.0
2,3,No,Cityace,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%,3005820.0
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%,6597557.0
4,5,No,Techdrill,IT Service,2011.0,"$10,573,990","7,435,363 Dollars",5573830.0,7%,5573830.0

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Date       10 non-null     str
 2   Name       10 non-null     str
 3   Companies  10 non-null     str
 4   Inception  10 non-null     float64
 5   Revenue    10 non-null     str
 6   Expenses   10 non-null     object
 7   Profit     10 non-null     float64
 8   Growth     10 non-null     str
 9   profit     10 non-null     float64
dtypes: float64(3), int64(1), object(1), str(5)
memory usage: 932.0+ bytes

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
min_max=MinMaxScaler()

In [44]:
profit_normalised=min_max.fit_transform(df[['Profit']])

In [45]:
profit_normalised.min()

np.float64(0.0)

In [46]:
profit_normalised.max()

np.float64(1.0)

In [47]:
df.head()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth,profit
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%,5274553.0
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",5573830.0,11412916.0,20%,11412916.0
2,3,No,Cityace,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%,3005820.0
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%,6597557.0
4,5,No,Techdrill,IT Service,2011.0,"$10,573,990","7,435,363 Dollars",5573830.0,7%,5573830.0

In [48]:
df['profit normalised']=profit_normalised

In [49]:
df.head()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth,profit,profit normalised
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%,5274553.0,0.255106
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",5573830.0,11412916.0,20%,11412916.0,0.945115
2,3,No,Cityace,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%,3005820.0,0.000079
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%,6597557.0,0.403824
4,5,No,Techdrill,IT Service,2011.0,"$10,573,990","7,435,363 Dollars",5573830.0,7%,5573830.0,0.288747

In [50]:
df_encoded=pd.get_dummies(df)

In [51]:
df.head()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth,profit,profit normalised
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%,5274553.0,0.255106
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",5573830.0,11412916.0,20%,11412916.0,0.945115
2,3,No,Cityace,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%,3005820.0,0.000079
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%,6597557.0,0.403824
4,5,No,Techdrill,IT Service,2011.0,"$10,573,990","7,435,363 Dollars",5573830.0,7%,5573830.0,0.288747

In [52]:
df_encoded.shape[1]

45

In [53]:
df_encoded.head()

,ID,Inception,Profit,profit,profit normalised,Date_No,Date_Yes,Name_Cityace,Name_Ganzlax,Name_Kayelectronics,...,"Expenses_6,482,465 Dollars","Expenses_7,429,377 Dollars","Expenses_7,435,363 Dollars","Expenses_7,591,189 Dollars",Growth_18%,Growth_20%,Growth_30%,Growth_4%,Growth_6%,Growth_7%
0,1,2009.0,5274553.0,5274553.0,0.255106,False,True,False,False,False,...,True,False,False,False,False,False,True,False,False,False
1,2,2010.0,11412916.0,11412916.0,0.945115,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,3,2012.0,3005820.0,3005820.0,0.000079,True,False,True,False,False,...,False,False,False,True,False,False,False,False,False,True
3,4,2013.0,6597557.0,6597557.0,0.403824,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,True
4,5,2011.0,5573830.0,5573830.0,0.288747,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 10 non-null     int64
 1   Date               10 non-null     str
 2   Name               10 non-null     str
 3   Companies          10 non-null     str
 4   Inception          10 non-null     float64
 5   Revenue            10 non-null     str
 6   Expenses           10 non-null     object
 7   Profit             10 non-null     float64
 8   Growth             10 non-null     str
 9   profit             10 non-null     float64
 10  profit normalised  10 non-null     float64
dtypes: float64(4), int64(1), object(1), str(5)
memory usage: 1012.0+ bytes

In [56]:
df.Name.unique()

<StringArray>
[       'Lamtone',      'Stripfind',        'Cityace',       'Mattouch',
      'Techdrill',       'Techline', 'Kayelectronics',        'Ganzlax',
   'Transtraxlax']
Length: 9, dtype: str

In [57]:
df.Companies.unique()

<StringArray>
['IT Service', 'Financial Services', 'Health', 'Government Services']
Length: 4, dtype: str

In [58]:
df.Date.unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [59]:
rom sklearn.preprocessing import LabelEncoder

SyntaxError: invalid syntax (2592739077.py, line 1)

In [63]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

In [64]:
df_encoded=label_encoder.fit_transform(df["Date"])

In [65]:
df_encoded

array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1])